/*
* Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.authserver.domain.repo;


import ht.bms.authserver.domain.BmsRole;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.Optional;




/**
 * Spring JPA Repository for BmsRoles
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BmsRolesRepository extends CrudRepository<BmsRole, BigDecimal> {
	
	Boolean existsByRoleId(BigDecimal roleId);
	Boolean existsByRoleName(String name);
	
	Optional<BmsRole> findByRoleId(BigDecimal roleId);
	Optional<BmsRole> findByRoleName(String name);

}