/*
 * Created on 21 May 2016 ( Time 16:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package ht.bms.authserver.domain.repo;


import ht.bms.authserver.domain.BmsUser;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;






/**
 * Spring JPA Repository for BmsUsers
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BmsUsersRepository extends CrudRepository<BmsUser, BigDecimal> ,JpaSpecificationExecutor<BmsUser> {
	
	//Boolean existsByNin(String nin);
	
}